// Generated by vite-ts-json-schema-generator plugin
// Don't modify this file

type JSONSchema = object;

declare module '*/type?schema' { export const SomeType: JSONSchema;export const SomeTypeIngerface: JSONSchema; }
declare module '*/importer?schema' { export const ImporterType: JSONSchema; }

